# Generated by Django 5.1.9 on 2025-08-07 15:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_product_stockentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockentry',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='packet_count',
        ),
        migrations.RemoveField(
            model_name='stockentry',
            name='product',
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('packet_count', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.product')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.stockentry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
